services:
  santastore:
    build: .
    env_file:
      - .env
    ports:
      - "9090:9090"
    volumes:
      - "/Users/c4lopsitta/PycharmProjects/secretsanta/santastores/:/app/santastores/"
    entrypoint: /bin/sh -c "uvicorn webpage:app --host 0.0.0.0 --port 9090 --workers 6"
